templates:
  ingest_workspace: '{project_root}/to_mvl/{vendor}/{date}/{scene}/{scene_shot}/{resolution}'
  egress_worksapce: '{project_root}/from_mvl/{vendor}/{date}/{scene}/{scene_shot}/{resolution}'
  