templates:
  ingest_workspace: '{project_root}/vault/to_mvl/{vendor}/{date}/{scene}/{shot}/{resolution}'
  egress_worksapce: '{project_root}/vault/from_mvl/{vendor}/{date}/{scene}/{shot}/{resolution}'
  